### ISSUE TITLE
Local links to assets need to be detected and the content included

### ISSUE THREAD

**Issue by liamcan** [Cannold/ghost#12]
Here's an example of an article which has a locally stored PDF.

* [ ] http://old.cannold.com/articles/article/positive-family-planning-letter/

**Comment by adamc00** [comment]
@liamcan, for the missing content, put the ton the manual fixup issue.

**Comment by thvu11** [comment]
Where can I get this PDF file? It doesn't include in assets folder. I do a quick search in `data/backup.yml`, it seems like anchor tag in format `<a href="/audio/....>` and  `<a href="/articles/....>` haven't had resource yet.

**Comment by adamc00** [comment]
Doing this manually. Was easier!
