### ISSUE TITLE
mapping old site locations to their home on new site

### ISSUE THREAD

**Issue by liamcan** [Cannold/ghost#17]
We need to set up permanent redirects for the old site in order to ensure people searching for leslie's old content aren't met with 404 errors. The first step in doing this is to create a script that can pull the old blog links and turn them into the new blogs format.

Output old and new as columns in a CSV file. We'll use that to setup a redirect later. 

Below I will provide a link to the old site location and the new site location (not including the domain) for each main category: 

**Events on old site look like:**

/events/event/capacity-building-for-abortion-rights-activists/

and we need them to look like:

/capacity-building-for-abortion-rights-activists/

**Articles on old site look like:**

/articles/article/is-vegetarianism-and-veganism-about-animal-welfare-or-moral-superiority/

and we need them to look like:

/is-vegetarianism-and-veganism-about-animal-welfare-or-moral-superiority/

**Research on old site look like:**

/articles/article/the-australian-pro-choice-movement-and-the-struggle-for-legal-clarity-liberal-laws-and-liberal-access-two-case-studies/

and we need them to look like:

the-australian-pro-choice-movement-and-the-struggle-for-legal-clarity-liberal-laws-and-liberal-access-two-case-studies/

**In-The-Media on old site look like:**

/articles/article/leslie-s-tedx-talk-passes-30-000-views/

and we need them to look like:

/leslie-s-tedx-talk-passes-30-000-views/

**Comment by adamc00** [comment]
Done. Thanks!
