### ISSUE TITLE
Add some info to README about running and populating

### ISSUE THREAD

**Issue by adamc00** [Cannold/ghost#6]
So I can check it out :)

**Comment by thvu11** [comment]
I've updated my README under my branch `populate-post-from-yaml`.

**Comment by adamc00** [comment]
Finally back to this @thvu11. I've tried following your README steps and they don't work on a clean checkout with no local docker images.

```
± |populate-post-from-yaml ?:1 ✗| → ./ghost.sh setup
Unable to find image 'ghost-exporter:master' locally
docker: Error response from daemon: pull access denied for ghost-exporter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

I think you will need to get the following bit working using `docker-compose` rather than a direct `docker` command to ensure the stack doesn't have external dependencies.

```
        docker run --env-file shared.env \
                --link=ghost_db_1 \
                --net ghost_default \
                --rm $IMAGE_NAME \
                perl /app/bin/setup-integration-service.pl

```

**Comment by thvu11** [comment]
I've switched it back to use `docker-compose`. The running and populating steps are similar as before.

**Comment by adamc00** [comment]
Done. Ta!
