### ISSUE TITLE
Missing content - publication history

### ISSUE THREAD

**Issue by liamcan** [Cannold/ghost#8]
This article has a publication history situated at the bottom of the page that is missing from the data dump. If we could extract and add that to the new blog format would be fantastic.

https://old.cannold.com/articles/article/is-vegetarianism-and-veganism-about-animal-welfare-or-moral-superiority/

**Comment by adamc00** [comment]
Note that there can be multiple publication history objects for a single article.

**Comment by liamcan** [comment]
This looks fixed for the example post, I assume its fixed all around but i'll keep this open for now just in case

**Comment by adamc00** [comment]
Done. Ta!
